#!/bin/sh

# Events
# ---------------------------------------------------------------------
nitrogen --restore & 
light -S 70
picom --experimental-backends &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
$HOME/.config/polybar/launch.sh &
deadd-notification-center &
setxkbmap -model pc104 -layout us,ru -variant ,, -option grp:alt_shift_toggle &
# ---------------------------------------------------------------------

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d I II III IV V VI VII   


# Smart Gaps
bspc config single_monocle true
bspc config gapless_monocle true

# Gaps 
bspc config border_width         2 
bspc config window_gap           8


# Set color border
bspc config focused_border_color '#81a1c1'
bspc config active_border_color  '#0C1115'
bspc config normal_border_color  '#0C1115'


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rulls open window 
bspc rule -a LibreWolf          desktop='^1'
bspc rule -a KotatogramDesktop  desktop='^2'
bspc rule -a mpv state=floating sticky=on
