#!/bin/sh

# Events
# ------------------------------------------------------------------------------
nitrogen --restore & 
picom --experimental-backends &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
$HOME/.config/polybar/launch.sh &
setxkbmap -model pc104 -layout us,ru -variant ,, -option grp:alt_shift_toggle &
mpd &
# ------------------------------------------------------------------------------

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d I II III IV V VI VII   


# Smart Gaps
bspc config single_monocle true
bspc config gapless_monocle true


# Gaps 
bspc config border_width         3 
bspc config window_gap           5


# Set color border
bspc config focused_border_color '#81a1c1'
bspc config active_border_color  '#0C1115'
bspc config normal_border_color  '#0C1115'


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rulls open window 
bspc rule -a LibreWolf          desktop='^1'
bspc rule -a KotatogramDesktop  desktop='^2'
bspc rule -a SublimeText       state=floating 
